version: "3"
services:
  dotnet:
    build:
      dockerfile: ci/docker/linux.Dockerfile
      context: ../../
    command: ["ci/docker/entrypoint.sh", "ci/build.sh"]
    volumes:
        - ${IMPROBABLE_CONFIG_DIR}:/home/user/.improbable
    environment:
        - CSHARP_TEMPLATE_BRANCH=${CSHARP_TEMPLATE_BRANCH}
        - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
